const money=/\b(?:r\$\s*)?(\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?|\d+(?:[.,]\d{1,2})?)\b/gi;
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const amount=s=>Number(s.replace(/\./g,'').replace(',','.'));
function isoDay(base,delta){const d=new Date(`${base}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+delta);return d.toISOString().slice(0,10)}
function dateFor(t,today){if(/anteontem/.test(t))return isoDay(today,-2);if(/ontem/.test(t))return isoDay(today,-1);return today}
function classify(t){if(/ipiranga|gasolina|etanol|diesel|combustivel/.test(t))return ['combustivel','Postos Ipiranga',.99];if(/mercado|supermercado|atacadao|assai/.test(t))return ['mercado',null,.96];if(/uber|99\b|taxi/.test(t))return ['transporte','Uber',.98];if(/wellhub|gympass|academia/.test(t))return ['academia',null,.98];return ['a_confirmar',null,.55]}
function tx(type,value,t,today,extra={}){const [category,merchant,confidence]=classify(t);return {type,amount:value,currency:'BRL',category,merchant,account:(t.match(/\b(nubank|inter|itau|bradesco|santander|caixa)\b/)||[])[1]||null,date:dateFor(t,today),installments:null,confidence,...extra}}
export function interpret(input,{today=new Date().toISOString().slice(0,10)}={}){const raw=String(input||'').trim();if(!raw||raw.length>4000)throw Object.assign(new Error('text_required_or_too_long'),{status:400});const t=normalize(raw);if(/paguei\s+a?\s*fatura/.test(t))return result('pay_card_bill',[tx('card_bill_payment',0,t,today,{category:'transferencia',confidence:.99})],.99,'Pagamento de fatura identificado; não vou duplicar as compras.');const transfer=t.match(/(?:transferi|transferencia|pix)\s+(?:de\s+)?(?:r\$\s*)?([\d.,]+).*?\b(?:do|da)\s+(nubank|inter|itau|bradesco|santander|caixa).*?\bpara\s+(?:o\s+)?(nubank|inter|itau|bradesco|santander|caixa)/);if(transfer)return result('internal_transfer',[{type:'transfer',amount:amount(transfer[1]),currency:'BRL',from_account:transfer[2],to_account:transfer[3],date:dateFor(t,today),category:'transferencia',installments:null,confidence:.99}],.99,'Transferência interna identificada; não será contabilizada como despesa.');const installment=t.match(/(?:comprei|gastei|paguei).*?(?:r\$\s*)?([\d.,]+).*?\b(?:em\s+)?(\d{1,2})\s*(?:x|vezes|parcelas)/);if(installment){const tr=tx('expense',amount(installment[1]),t,today,{installments:Number(installment[2])});return result('create_transactions',[tr],Math.min(tr.confidence,.94),`Entendi uma compra de R$ ${tr.amount.toFixed(2)} em ${tr.installments} parcelas. Confirma?`)}const segments=t.split(/\s+e\s+(?=(?:hoje|ontem|anteontem|gastei|paguei|comprei|coloquei))/);const transactions=[];for(const seg of segments){const ms=[...seg.matchAll(money)];for(const m of ms){if(Number(m[1])>0)transactions.push(tx(/recebi|entrou|ganhei/.test(seg)?'income':'expense',amount(m[1]),seg,today))}}if(!transactions.length)return {intent:'unknown',resolution_layer:'economy_ai',confidence:.35,requires_confirmation:true,transactions:[],reply:'Não consegui resolver com segurança. Preciso de mais contexto ou da IA econômica.'};const conf=Math.min(...transactions.map(x=>x.confidence));return result('create_transactions',transactions,conf,transactions.length>1?`Entendi ${transactions.length} lançamentos. Confira valores e datas antes de confirmar.`:'Entendi o lançamento. Confirma?')}
function result(intent,transactions,confidence,reply){return {intent,resolution_layer:confidence>=.97?'deterministic':confidence>=.9?'global_knowledge':'economy_ai',confidence,requires_confirmation:true,transactions,reply}}
