import {access} from 'node:fs/promises';
for (const path of [
  'index.html',
  'app.js',
  'admin.js',
  'styles.css',
  'vercel.json',
  'api/v1/health.js',
  'api/v1/dashboard.js',
  'api/v1/admin/snapshot.js',
  'api/v1/brain/preview.js',
  'api/v1/brain/interpret.js',
  'api/v1/audio/transcribe.js',
  'api/v1/channels/whatsapp/message.js',
  'lib/admin-auth.js',
  'lib/api-auth.js',
  'lib/brain-client.js',
  'lib/brain.js',
  'lib/channel-links.js',
  'lib/mf24-prod.js',
  'lib/openai.js',
  'lib/orchestrator.js',
  'lib/audio.js',
  'lib/idempotency.js',
]) await access(path);
console.log('Build validation passed');
